import type { OptionsAnalyticsSnapshot } from '@0dtetrader/shared-types';

export function makeOptionsAnalyticsSnapshot(
  overrides: Partial<OptionsAnalyticsSnapshot> = {},
): OptionsAnalyticsSnapshot {
  const snapshot: OptionsAnalyticsSnapshot = {
    scope: {
      symbol: 'SPY',
      rootSymbol: 'SPY',
      expiration: '2026-07-19',
      settlementStyle: 'pm',
      observedAt: '2026-07-19T14:30:10.000Z',
      settlementAt: '2026-07-19T20:00:00.000Z',
      spot: 500,
      forward: 500.25,
    },
    exposureUnit: '$ delta change per 1% underlying move',
    quality: {
      quoteAsOf: '2026-07-19T14:30:08.000Z',
      greeksAsOf: '2026-07-19T14:30:06.000Z',
      oiEffectiveDate: '2026-07-18',
      feedMode: 'realtime',
      coverage: { contractsTotal: 10, contractsIncluded: 8, ratio: 0.8 },
      status: 'partial',
      warnings: ['Two crossed quotes excluded'],
      calculationVersion: 'options-analytics-v1',
      cacheStatus: 'fresh',
    },
    structure: {
      callGammaExposure: 900,
      putGammaExposure: 500,
      grossGammaExposure: 1_400,
      callDeltaNotional: 2_000_000,
      putDeltaNotional: -1_500_000,
      callWall: 505,
      putWall: 495,
      grossGammaConcentration: 0.4,
      maxOpenInterestStrike: 500,
    },
    scenarios: {
      callPutDealerProxy: {
        assumption: 'Calls short and puts long dealer proxy',
        gammaExposure: 400,
        deltaNotional: -100_000,
        strikeGammaExposures: [
          { strike: 495, gammaExposure: 300 },
          { strike: 505, gammaExposure: -400 },
        ],
        gammaRoots: [497.5, 502.5],
        primaryGammaRoot: 497.5,
      },
    },
    impliedRange: {
      lower: 493,
      upper: 507,
      confidence: 0.68,
      label: 'model-implied 68% range',
      atmIv: 0.2,
      straddleLower: 492,
      straddleUpper: 508,
    },
    strikes: [
      {
        strike: 495,
        call: {
          openInterest: 100,
          volume: 12,
          impliedVolatility: 0.21,
          delta: 0.7,
          gamma: 0.02,
          gammaExposure: 100,
          deltaNotional: 3_500_000,
          markedOiValue: 12_000,
          relativeSpread: 0.08,
          roundTripCost: 800,
          bidSize: 20,
          askSize: 18,
          multiplier: 100,
        },
        put: {
          openInterest: 80,
          volume: 10,
          impliedVolatility: 0.22,
          delta: -0.3,
          gamma: 0.02,
          gammaExposure: 400,
          deltaNotional: -1_200_000,
          markedOiValue: 8_000,
          relativeSpread: 0.12,
          roundTripCost: 600,
          bidSize: 15,
          askSize: 14,
          multiplier: 100,
        },
        grossGammaExposure: 500,
        totalOpenInterest: 180,
      },
      {
        strike: 505,
        call: {
          openInterest: 120,
          volume: 16,
          impliedVolatility: 0.2,
          delta: 0.35,
          gamma: 0.025,
          gammaExposure: 400,
          deltaNotional: 2_100_000,
          markedOiValue: 20_000,
          relativeSpread: 0.05,
          roundTripCost: 500,
          bidSize: 25,
          askSize: 22,
          multiplier: 100,
        },
        put: null,
        grossGammaExposure: 400,
        totalOpenInterest: 120,
      },
    ],
  };
  return { ...snapshot, ...overrides };
}
