#!/usr/bin/env bash
set -euo pipefail

# Reads .env from the repo root and generates a Swift file
# with compile-time constants, so the iOS app can control
# API_BASE_URL from the same .env used by the API and desktop.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"
OUTPUT_DIR="$SCRIPT_DIR/../0dteTrader/App"
OUTPUT_FILE="$OUTPUT_DIR/GeneratedEnvironment.swift"

API_BASE_URL="${API_BASE_URL:-}"

if [[ -f "$ENV_FILE" ]]; then
	# Strip comments and blank lines, then extract API_BASE_URL.
	FILE_API_BASE_URL=$(grep '^API_BASE_URL=' "$ENV_FILE" | head -1 | sed 's/^API_BASE_URL=//' | tr -d '"' | tr -d "'")
	if [[ -n "$FILE_API_BASE_URL" ]]; then
		API_BASE_URL="$FILE_API_BASE_URL"
	fi
fi

if [[ -z "$API_BASE_URL" ]]; then
	API_BASE_URL="http://localhost:3000"
fi

cat >"$OUTPUT_FILE" <<EOF
// Generated by scripts/generate-env.sh — do not edit.
import Foundation

enum GeneratedEnvironment {
    static let apiBaseURL: String = "$API_BASE_URL"
}
EOF

echo "[generate-env] API_BASE_URL = $API_BASE_URL"
